alunos/urls.py
from django.conf.urls import patterns, include, url

from . import views


urlpatterns = patterns('alunos.views',
    # url(r'^$', 'lista', name='lista'),
    url(r'^$', 'lista', name='lista'),
    url(r'^create/$', 'create', name='create'),
    url(r'^delete/(?P<codigoAluno>\d+)$', 'delete', name='delete'),
    url(r'^update/(?P<codigoAluno>\d+)$', 'update', name='update'),
)

core/urls.py
from django.conf.urls import url
from core.views import  home, lista, novo, atualiza, deletar


urlpatterns = [
    url(r'^$', home),
    url(r'^lista', lista),
    url(r'^novo/$', novo),
    url(r'^atualizar/(?P<id>\d+)/$', atualiza, name='atualizar'),
    url(r'^deletar/(?P<id>\d+)/$', deletar, name='deletar'),
]

djangotest/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^blog/', include('core.urls', namespace='core')),
    url(r'^alunos/', include('alunos.urls', namespace='alunos')),
    url(r'^turmas/', include('turmas.urls', namespace='turmas')),
    url(r'^', include('core.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

turmas/urls.py
from django.conf.urls import patterns, include, url

from . import views


urlpatterns = patterns('turmas.views',
    # url(r'^', 'lista', name='lista'),
    url(r'^lista', 'lista', name='lista'),
    url(r'^create/$', 'create', name='create'),
    url(r'^delete/(?P<codigoTurma>\d+)$', 'delete', name='delete'),
    url(r'^update/(?P<codigoTurma>\d+)$', 'update', name='update'),
)

alunos/models.py
# -*- coding: utf-8 -*-
from django.db import models

class Aluno(models.Model):

    codigoAluno = models.IntegerField(primary_key=True) 
    nomeAluno   = models.CharField('Nome completo', max_length=200)
    cpf         = models.CharField('CPF', max_length=14, unique=True)
    telefone    = models.CharField('Telefone', max_length=(11))
    dataNasc    = models.DateField('Data de nascimento')

    turma = models.ForeignKey('Turma')

    def __unicode__(self):
        return self.nomeAluno

class Turma(models.Model):
    
    codigoTurma = models.IntegerField(primary_key=True) 
    nomeTurma   = models.CharField('Nome completo', max_length=200)
    descricaoTurma = models.TextField()


    class Meta:
        verbose_name = u'Turma'
        verbose_name_plural = u'Turmas'

    def __unicode__(self):
        return self.nomeTurma

core/models.py
from __future__ import unicode_literals
from django.db import models


class Post(models.Model):
	titulo = models.CharField(max_length = 100)
	texto  = models.TextField()

	def __str__(self):
		return self.titulo

turmas/models.py
# -*- coding: utf-8 -*-
from django.db import models

class Aluno(models.Model):
    """
    Cadastro de Alunos
    """
    codigoAluno = models.IntegerField(primary_key=True) 
    nomeAluno   = models.CharField('Nome completo', max_length=200)
    cpf         = models.CharField('CPF', max_length=14, unique=True)
    telefone    = models.CharField('Telefone', max_length=(11))
    dataNasc    = models.DateField('Data de nascimento')

    turma = models.ForeignKey('Turma')

    def __unicode__(self):
        return self.nomeAluno

class Turma(models.Model):
    
    codigoTurma = models.IntegerField(primary_key=True) 
    nomeTurma   = models.CharField('Nome da turma', max_length=200)
    descricaoTurma = models.TextField('Descrição', )


    class Meta:
        verbose_name = u'Turma'
        verbose_name_plural = u'Turmas'

    def __unicode__(self):
        return self.nomeTurma

alunos/forms.py
from django.forms import ModelForm
from alunos.models import Aluno
from alunos.models import Turma


class AlunoForm(ModelForm):
    class Meta:
    	model = Aluno
    	fields = ['turma','nomeAluno', 'cpf','telefone', 'dataNasc']

class TurmaForm(ModelForm):
    class Meta:
        model = Turma
        fields = ['codigoTurma', 'nomeTurma', 'descricaoTurma']

core/forms.py
from django.forms import ModelForm
from core.models import Post


class PostForm(ModelForm):
	class Meta:
		model = Post
		fields = ['titulo', 'texto']

turmas/forms.py
from django.forms import ModelForm
from alunos.models import Aluno
from alunos.models import Turma



class AlunoForm(ModelForm):
    class Meta:
    	model = Aluno
    	fields = ['nomeAluno', 'cpf','telefone', 'dataNasc', 'turma']

class TurmaForm(ModelForm):
    class Meta:
        model = Turma
        fields = ['nomeTurma', 'descricaoTurma']

alunos/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from forms import AlunoForm
from alunos.models import Aluno
from django.shortcuts import render, redirect
from alunos.models import Aluno
from alunos.forms import AlunoForm


def lista(request):
	alunos = Aluno.objects.all()
	context = RequestContext(request, {'alunos': alunos})
	return render_to_response('aluno/list.html', context)


def create(request):
	form = AlunoForm(request.POST or None)
	
	if request.method == 'POST' and form.is_valid():
		form.save()
		return redirect('/alunos/')

	context = RequestContext(request, {'form': form})
	return render_to_response('aluno/create.html', context)


def delete(request, codigoAluno):
    aluno = Aluno.objects.get(pk=codigoAluno)

    if request.method == "POST":
        aluno.delete()
        return HttpResponseRedirect('/alunos/')

    context = RequestContext(request, {'aluno': aluno})
    return render_to_response('aluno/delete.html', context)


def update(request, codigoAluno):
	alunos = Aluno.objects.get(pk=codigoAluno)
	
	if request.method == 'POST':
		form = AlunoForm(request.POST, instance=alunos)

		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/alunos/')

	else:
		form = AlunoForm(instance=alunos)
		
	context = RequestContext(request, {'form': form, 'codigoAluno': codigoAluno})
	return render_to_response('aluno/update.html', context)	

core/views.py
from django.shortcuts import render, redirect
from core.models import Post
from core.forms import PostForm

def home(request):
	return render(request, 'landpage/index.html')

def lista(request):
	lista = Post.objects.all().order_by('-id')
	return render(request, 'core/lista.html', {'lista_post':lista})

def novo(request):
	form = PostForm(request.POST or None)

	if request.method == 'POST':
		if form.is_valid():
			form.save()
			return redirect(lista)

	return render(request, 'core/novo.html', {'form': form})

def atualiza(request, id):
	post = Post.objects.get(id=id)
	form = PostForm(request.POST or None, instance=post)

	if form.is_valid():
		form.save()
		return redirect(lista)

	return render(request, 'core/novo.html', {'form':form})

def deletar(request, id):
    post = Post.objects.get(id=id)
    post.delete()
    return redirect(lista)

turmas/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from forms import TurmaForm
from turmas.models import Turma
from django.shortcuts import render, redirect
from turmas.models import Turma
from turmas.forms import TurmaForm


def lista(request):
	turmas = Turma.objects.all()
	context = RequestContext(request, {'turmas': turmas})
	return render_to_response('turma/list.html', context)


def create(request):
	form = TurmaForm(request.POST or None)
	
	if request.method == 'POST' and form.is_valid():
		form.save()
		return redirect('/turmas/lista')

	context = RequestContext(request, {'form': form})
	return render_to_response('turma/create.html', context)


def delete(request, codigoTurma):
    turma = Turma.objects.get(pk=codigoTurma)

    if request.method == "POST":
        turma.delete()
        return HttpResponseRedirect('/turmas/')

    context = RequestContext(request, {'turma': turma})
    return render_to_response('turma/delete.html', context)


def update(request, codigoTurma):
	turmas = Turma.objects.get(pk=codigoTurma)
	
	if request.method == 'POST':
		form = TurmaForm(request.POST, instance=turmas)

		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/turmas/')

	else:
		form = TurmaForm(instance=turmas)
		
	context = RequestContext(request, {'form': form, 'codigoTurma': codigoTurma})
	return render_to_response('turma/update.html', context)	

alunos/templates/aluno/create.html
{% extends "base.html" %}


{% block content %}
<legend>Cadastrando</legend>
<form method="POST">
	{% csrf_token %}
	{{ form }}
	<input type="submit" value="Salvar" class="btn">
</form>

{% endblock %}

alunos/templates/aluno/delete.html
{% extends "base.html" %}
{% block content %}
<legend>Excluir?</legend>
    <p>{{ aluno.nomeAluno }}
    <p>{{ aluno.cpf }}</p>
    <p>{{ aluno.telefone }}</p>
    <p>{{ aluno.dataNasc }}</p>
    <form action="{% url 'alunos:delete' aluno.codigoAluno %}" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Sim">
        <a href="{% url 'alunos:lista' %}" class="btn">Cancelar</a>
    </form>
{% endblock %}

alunos/templates/aluno/list.html
{% extends "base.html" %}
{% block content %}
<h2>Alunos</h2>
    <a href="{% url 'alunos:create' %}" class="btn btn-primary">Cadastrar</a>

    {% if alunos.count > 0 %}
    <legend>Listando meus registros!</legend>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Nome</th>
            <th>CPF</th>
            <th>Data de nascimento</th>
            <th>Turma</th>
            <th>Ações</th>
        </tr>
        </thead>
        <tbody>
        {% for aluno in alunos %}
            <tr> 
                <td>{{ aluno.nomeAluno }}</td> 
                <td>{{ aluno.cpf }}</td>
                <td>{{ aluno.dataNasc }}</td>
                <td>{{ aluno.turma }}</td>
                <td><a href="{% url 'alunos:update' aluno.codigoAluno %}" class="btn btn-small"><i class="icon-edit"
                                                                                            title="Alterar"></i></a>
                    <a href="{% url 'alunos:delete' aluno.codigoAluno %}" class="btn btn-small"><i class="icon-remove"
                                                                                            title="Excluir"></i></a>
                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}
{% endblock %}

alunos/templates/aluno/update.html
{% extends "base.html" %}


{% block content %}
	<legend>Editando!</legend>
	<form action="{% url 'alunos:update' codigoAluno %}" method="POST">
		{% csrf_token %}
		{{ form }}
		<input type="submit" value="Salvar" class="btn">
	</form>
{% endblock %}

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>MovTI</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Simples Crud Django">
  <meta name="author" content="Breno Thales">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap-responsive.min.css' %}" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->
      
    </head>

    <body>

      <div class="navbar navbar-inverse navbar-fixed-top  ">
        <div class="navbar-inner">
          <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/">MovTi</a>
            <div class="nav-collapse collapse">
              <ul class="nav">
                <li><a href="{% url 'turmas:lista' %}">Turma</a></li>
                <li><a href="{% url 'alunos:lista' %}">Aluno</a></li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>

      <div class="container">
        
        {% block content %}
        
        {% endblock %}
        
        <footer>
          <p>&copy; Breno Thales</p>
        </footer>

      </div> 
    </body>
    </html>

core/templates/core/index.html
<!doctype html>
<html lang="pt-BR">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<h1>Hello World</h1>
</body>
</html>

core/templates/core/lista.html
<!doctype html>
<html lang="pt-BR">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<h1>Lista dos posts</h1>
	<a href="/novo">Novo</a> 
	{% for post in lista_post %}
		<article>
			<h2>{{ post.titulo }}</h2>
			    {{ post.texto }}
			    <a href="{% url 'atualizar' post.id %}"Atualizar>Atualizar</a> 
			    <a href="{% url 'deletar' post.id %}"Atualizar>Deletar</a> 
		</article>
	{% endfor %}
</body>
</html>

core/templates/core/novo.html
<!doctype html>
<html lang="pt-BR">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<h1>Novo posts</h1>
		<form method="POST">
		    {% csrf_token %}
		    {{form}} <br>
		  <button type="submit">Salvar</button>
		</form>
</body>
</html>

core/templates/index.html
{% extends "base.html" %}
{% block content %}
Welcome to my project!
{% endblock %}

core/templates/landpage/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Simples Teste em Django</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'landpage/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'landpage/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'landpage/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'landpage/css/creative.min.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="/">APP DJANGO</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'turmas:lista' %}">Turma</a>
                    </li>
                    <li>
                        <a href="{% url 'alunos:lista' %}">Alunos</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading">Falicidade em desenvolvimento com melhor Framework que mais crescer na web</h1>
                <hr>
                <p>Uma simples aplicação em Django para teste de proficiência em desenvolvimento Web para empresa MovTI</p>
                <a href="#about" class="btn btn-primary btn-xl page-scroll">mais informação</a>
            </div>
        </div>
    </header>

    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Desafio</h2>
                    <hr class="light">
                    <p class="text-faded">Descrição do desafio: Você deve desenvolver uma aplicação que contenha um CRUD (Create, remove, update and delete), em python utilizando o framework django.</p>
                    <a href="{% url 'alunos:lista' %}" class="page-scroll btn btn-default btn-xl sr-button">Conhecer</a>
                </div>
            </div>
        </div>
    </section>

    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Informações</h2>
                    <hr class="primary">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-google text-primary sr-icons"></i>
                        <h3>breno.thales</h3>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-github text-primary sr-icons"></i>
                        <h3>brenothales</h3>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-linkedin-square text-primary sr-icons"></i>
                        <h3>brenothales</h3>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-mobile text-primary sr-icons"></i>
                        <h3>48.99933-3433</h3>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <aside class="bg-dark">
        <div class="container text-center">
            <div class="call-to-action">
                <h2>Download do Código</h2>
                <a href="https://github.com/brenothales/crud-django" class="btn btn-default btn-xl sr-button" data-sr-id="7" style="; visibility: visible;  -webkit-transform: translateY(0) scale(1); opacity: 1;transform: translateY(0) scale(1); opacity: 1;-webkit-transition: all 0.35s ease 0s, -webkit-transform 1s cubic-bezier(0.6, 0.2, 0.1, 1) 0.2s, opacity 1s cubic-bezier(0.6, 0.2, 0.1, 1) 0.2s; transition: all 0.35s ease 0s, transform 1s cubic-bezier(0.6, 0.2, 0.1, 1) 0.2s, opacity 1s cubic-bezier(0.6, 0.2, 0.1, 1) 0.2s; ">GITHUB</a>
            </div>
        </div>
    </aside>

</body>

</html>

turmas/templates/turma/create.html
{% extends "base.html" %}
<form action="/url/to/submit/" method="post">
	{% csrf_token %}
	<div class="form-actions">
		<button type="submit" class="btn btn-primary">Submit</button>
	</div>
</form>

{% block content %}
<legend>Cadastrando</legend>
<form method="POST">
	{% csrf_token %}
	{{ form }} <br>
	<input type="submit" value="Salvar" class="btn">
</form>

{% endblock %}

turmas/templates/turma/delete.html
{% extends "base.html" %}
{% block content %}
<legend>Excluir?</legend>
    <p>{{ turma.nomeTurma }}
    <form action="{% url 'turmas:delete' turma.turma %}" method="POST">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Sim">
        <a href="{% url 'turmas:lista' %}" class="btn">Cancelar</a>
    </form>
{% endblock %}

turmas/templates/turma/list.html
{% extends "base.html" %}
{% block content %}
<h2>Turma</h2>
    <a href="{% url 'turmas:create' %}" class="btn btn-primary">Cadastrar</a>

    {% if turmas.count > 0 %}
    <legend>Listando meus registros!</legend>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Código da Turma</th>
            <th>Nome da Turma</th>
        </tr>
        </thead>
        <tbody>
        {% for turma in turmas %}
            <tr> 
                <td>{{ turma.codigoTurma }}</td> 
                <td>{{ turma.nomeTurma }}</td>
                <td><a href="{% url 'turmas:update' turma.codigoTurma %}" class="btn btn-small"><i class="icon-edit"
                                                                                            title="Alterar"></i></a>
                    <a href="{% url 'turmas:delete' turma.codigoTurma %}" class="btn btn-small"><i class="icon-remove"
                                                                                            title="Excluir"></i></a>
                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}
{% endblock %}

turmas/templates/turma/update.html
{% extends "base.html" %}


{% block content %}
	<legend>Editando!</legend>
	<form action="{% url 'turmas:update' codigoTurma %}" method="POST">
		{% csrf_token %}
		{{ form }}
		<input type="submit" value="Salvar" class="btn">
	</form>
{% endblock %}